# Generated by Django 3.2.12 on 2022-03-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220306_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goup',
            new_name='Group',
        ),
    ]
